stages:
  - update
  - build-front
  - build-api
  - deploy-api
  - env
  - build
  - deploy
.before_script_template:
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install rsync openssh-client zip unzip -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n \tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'echo -e "Host * \n  " >> ~/.ssh/config'
update:
  extends: .before_script_template
  stage: update
  environment: prod
  script:
    - ssh root@149.202.94.4 "cd /var/www/food-delivery/ && git fetch --all && git reset --hard origin/main && git pull origin main"
  only:
    - master
  when: always
build-front:
  extends: .before_script_template
  stage: build-front
  environment: prod
  script:
    - ssh root@149.202.94.4 "cd /var/www/food-delivery/ && npm run build front"
  only:
    - master

build-api:
  extends: .before_script_template
  stage: build-api
  environment: prod
  script:
    - ssh root@149.202.94.4 "cd /var/www/food-delivery && npm run build api && pm2 restart food-delivery"
  only:
    - master
