version: "2"
services:
  food-server:
    container_name: delivery-api
    build:
      context: .
      dockerfile: ./ops/Dockerfile.api
    ports:
      - "3051:3333"
    restart: always
  food-client:
    container_name: delivery-front
    build:
      context: ../front/.
      dockerfile: ./ops/Dockerfile.front
    ports:
      - "3050:80"
