FROM node:lts-alpine
WORKDIR /app
COPY ./dist/apps/api .
COPY ./dist/apps/api/package.json ./
COPY ./package-lock.json ./
ENV PORT=3333
EXPOSE ${PORT}
RUN npm install --production
RUN npm install tslib@2.0.0
CMD node ./main.js