# production environment
FROM nginx:stable-alpine
COPY ./dist/apps/front /usr/share/nginx/html
COPY ./ops/nginx/nginx.front.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
